✨feature: verify sftp (#79)
* ✨feature: verify sftp

* ✨feature: add  Update Helm Chart Readme workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,6 +41,20 @@ jobs:
           sudo mc config host add local http://127.0.0.1:9000 ${{ env.MINIO_ROOT_USER }} ${{ env.MINIO_ROOT_PASSWORD }} --api S3v4
           sudo mc mb local/backup
 
+      - name: Setup SFTP
+        run: |
+          mkdir -p test/gh-actions/sftp/ssh
+          mkdir -p test/backups/sftp
+          ssh-keygen -t rsa -b 4096 -f test/gh-actions/sftp/ssh/id_rsa -q -N "YOUR_PASSPHRASE_HERE" < /dev/null
+          sudo chown 1001:1001 test/backups/sftp
+          docker run -d --name sftp \
+              -v `pwd`/test/gh-actions/sftp/ssh/id_rsa.pub:/home/mgob/.ssh/keys/id_rsa.pub:ro \
+              -v `pwd`/test/backups/sftp:/home/mgob/upload \
+              --ulimit nofile=65536:65536 \
+              -p 2222:22 \
+              atmoz/sftp:alpine \
+              mgob:secret:1001::upload
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
@@ -95,7 +109,7 @@ jobs:
           echo '💥💥💥💥💥💥💥💥 Get mgob Version 💥💥💥💥💥💥💥💥💥💥'
           curl http://127.0.0.1:8090/version | tee version.txt
           echo '💥💥💥💥💥💥💥💥 Get mgob Metrics 💥💥💥💥💥💥💥💥💥💥'
-          curl http://127.0.0.1:8090/metrics | tee metrics.txt
+          curl http://127.0.0.1:8090/metrics > metrics.txt
           echo '💥💥💥💥💥💥💥💥 Get mgob logs 💥💥💥💥💥💥💥💥💥💥'
           logs=$(docker logs mgob 2>&1)
           echo "$logs" | tee logs.txt
@@ -129,7 +143,11 @@ jobs:
             echo "Azure integration test failed, check if the connection string is expired"
             exit 1
           fi
-          
+          # verify for sftp
+          if ! grep -q "SFTP upload finished" logs.txt; then
+            echo "SFTP integration test failed"
+            exit 1
+          fi
       - name: Upload file as artifact
         uses: actions/upload-artifact@v3
         with:
@@ -201,22 +219,3 @@ jobs:
           push: true
           cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mgob:buildcache-dev
           cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mgob:buildcache-dev,mode=max
-  update-readme:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.pull_request.head.ref }}
-
-      - name: Run helm-docs
-        run: |
-          curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_x86_64.deb -o helm-docs.deb \
-          && sudo dpkg -i helm-docs.deb \
-          && rm helm-docs.deb \
-          && helm-docs --sort-values-order file
-
-      - name: Commit bump
-        uses: EndBug/add-and-commit@v9.1.1
-        with:
-          message: "Regenerate chart README.md"
-          add: "charts/mgob/README.md"
