✨feature: update e2e test (#75)
* ✨feature: update e2e test

* ✨feature: add gcloud e2e test

* ✨feature: throw  keyfilepath missing error

* 📄 docs: update

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,7 +14,7 @@ jobs:
       MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
     services:
       mongodb:
-        image: mongo:4.2.8
+        image: mongo:7.0.1
         ports:
           - 27017:27017
       minio:
@@ -72,6 +72,12 @@ jobs:
           cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mgob:buildcache-dev
           cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/mgob:buildcache-dev,mode=max
 
+      - name: Setup key
+        env:
+          GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
+        run: |
+          echo "$GCLOUD_KEY" | base64 --decode > ${{ github.workspace }}/test/gh-actions/gcloud.json
+
       - name: Run Mgob image
         run: >
           docker run -d 
@@ -82,7 +88,7 @@ jobs:
           ${{ github.repository }}:${{ env.APP_VERSION }}.${{ github.run_number }}
       - name: Verify mgob backup
         run: |
-          sleep 60
+          sleep 90
           echo '💥💥💥💥💥💥💥💥 Get mgob Version 💥💥💥💥💥💥💥💥💥💥'
           curl http://127.0.0.1:8090/version | tee version.txt
           echo '💥💥💥💥💥💥💥💥 Get mgob Metrics 💥💥💥💥💥💥💥💥💥💥'
@@ -91,7 +97,7 @@ jobs:
           logs=$(docker logs mgob 2>&1)
           echo "$logs" | tee logs.txt
           echo '💥💥💥💥💥💥💥💥 verify mgob backup 💥💥💥💥💥💥💥💥💥💥'
-          
+          # verify for s3
           if ! grep -q "S3 upload finished" logs.txt; then
             echo "S3 integration test failed"
             exit 1
@@ -100,7 +106,7 @@ jobs:
             echo "Local backup integration test failed"
             exit 1
           fi
-          # test for no-local plan
+          # verify for no-local plan
           if grep -q "Local backup finished.*plan=no-local" logs.txt; then
             echo "Skip Local backup integration test failed"
             exit 1
@@ -109,6 +115,11 @@ jobs:
           if [[ $(ls -A "${{ github.workspace }}/test/backups/no-local") ]]; then
               echo "There are files in the directory."
               exit 1
+          fi
+          # verify for gcloud
+          if ! grep -q "GCloud upload finished Copying" logs.txt; then
+            echo "GCloud integration test failed"
+            exit 1
           fi
           
       - name: Upload file as artifact
@@ -154,13 +165,13 @@ jobs:
       - name: Verify metrics
         run: |
           echo 'Verify metrics'
-          # should find "mgob_scheduler_backup_total{plan="mongo-test",status="200"} 1"
-          if ! grep -q "mgob_scheduler_backup_total{plan=\"mongo-test\",status=\"200\"} 1" metrics.txt; then
+          # should find "mgob_scheduler_backup_total{plan="mongo-test",status="200"}"
+          if ! grep -q "mgob_scheduler_backup_total{plan=\"mongo-test\",status=\"200\"}" metrics.txt; then
             echo "Metrics integration test failed for mongo-test"
             exit 1
           fi
-          # should find "mgob_scheduler_backup_total{plan="no-local",status="200"} 1"
-          if ! grep -q "mgob_scheduler_backup_total{plan=\"no-local\",status=\"200\"} 1" metrics.txt; then
+          # should find "mgob_scheduler_backup_total{plan="no-local",status="200"}"
+          if ! grep -q "mgob_scheduler_backup_total{plan=\"no-local\",status=\"200\"}" metrics.txt; then
             echo "Metrics integration test failed for no-local"
             exit 1
           fi
