🔵 other: disable azure for now

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -103,6 +103,7 @@ jobs:
           -v ${{ github.workspace }}/test/gh-actions:/config \
           -v ${{ github.workspace }}/test/backups:/storage \
           ${{ github.repository }}:${{ env.APP_VERSION }}.${{ github.run_number }}
+
       - name: Verify mgob backup
         run: |
           sleep 90
@@ -138,11 +139,11 @@ jobs:
             echo "GCloud integration test failed"
             exit 1
           fi
-          verify for azure
-          if ! grep -q "Azure upload finished" logs.txt; then
-            echo "Azure integration test failed, check if the connection string is expired"
-            exit 1
-          fi
+          # # verify for azure
+          # if ! grep -q "Azure upload finished" logs.txt; then
+          #   echo "Azure integration test failed, check if the connection string is expired"
+          #   exit 1
+          # fi
           # verify for sftp
           if ! grep -q "SFTP upload finished" logs.txt; then
             echo "SFTP integration test failed"
