Add ARM64 Support and Optimize Build Process (#145)
* Add ARM64 Support and Optimize Build Process

---------

Co-authored-by: Sam Lin <456807+maxisam@users.noreply.github.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -79,6 +79,7 @@ jobs:
         if: github.event_name == 'workflow_dispatch'
         uses: docker/build-push-action@v6
         with:
+          platforms: linux/amd64
           build-args: |
             BUILD_DATE=${{ env.NOW }}
             VCS_REF=${{ github.sha }}
@@ -99,6 +100,7 @@ jobs:
         if: github.event_name == 'pull_request'
         uses: docker/build-push-action@v6
         with:
+          platforms: linux/amd64
           build-args: |
             BUILD_DATE=${{ env.NOW }}
             VCS_REF=${{ github.sha }}
@@ -139,6 +141,41 @@ jobs:
           -v ${{ github.workspace }}/test/gh-actions:/config \
           -v ${{ github.workspace }}/test/backups:/storage \
           ${{ github.repository }}:${{ env.APP_VERSION }}.${{ github.run_number }}
+
+      - name: Verify Mgob container is running
+        run: |
+          if [ "$(docker inspect -f '{{.State.Status}}' mgob)" != "running" ]; then
+            echo "Mgob container is not running!"
+            docker logs mgob
+            exit 1
+          fi
+          echo "Mgob container is running."
+
+      - name: Check Mgob container logs for startup errors
+        run: |
+          if docker logs mgob 2>&1 | grep -iq "error"; then
+            echo "Error found in Mgob startup logs!"
+            docker logs mgob
+            exit 1
+          fi
+          echo "No errors in Mgob startup logs."
+
+      - name: Wait for Mgob service to be ready
+        run: |
+          echo 'Waiting for Mgob to be ready...'
+          for i in {1..10}; do
+            if curl -s http://127.0.0.1:8090/version -o /dev/null; then
+              echo "Mgob is ready!"
+              break
+            elif [ "$i" -eq "10" ]; then
+              echo "Mgob not ready after multiple attempts."
+              docker logs mgob
+              exit 1
+            fi
+            echo "Waiting for Mgob... retrying in 5 seconds"
+            sleep 5
+          done
+          echo 'Mgob service is available.'
 
       - name: Verify mgob backup for PR
         run: |
@@ -252,7 +289,9 @@ jobs:
         if: github.event_name == 'workflow_dispatch'
         uses: docker/build-push-action@v6
         with:
+          platforms: linux/amd64,linux/arm64
           build-args: |
+            BUILDKIT_MULTI_PLATFORM=1
             BUILD_DATE=${{ env.NOW }}
             VCS_REF=${{ github.sha }}
             VERSION=${{ env.APP_VERSION }}.${{ github.run_number }}
