✨feature: verify azure

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -75,8 +75,10 @@ jobs:
       - name: Setup key
         env:
           GCLOUD_KEY: ${{ secrets.GCLOUD_KEY }}
+          AZURE_CONNECTIONSTRING: ${{ secrets.AZURE_CONNECTIONSTRING }}
         run: |
           echo "$GCLOUD_KEY" | base64 --decode > ${{ github.workspace }}/test/gh-actions/gcloud.json
+          sed -i "s|BlobEndpoint|$AZURE_CONNECTIONSTRING|g" /test/gh-actions/mongo-test.yml
 
       - name: Run Mgob image
         run: >
@@ -119,6 +121,11 @@ jobs:
           # verify for gcloud
           if ! grep -q "GCloud upload finished Copying" logs.txt; then
             echo "GCloud integration test failed"
+            exit 1
+          fi
+          # verify for azure
+          if ! grep -q "Azure upload finished Copying" logs.txt; then
+            echo "Azure integration test failed, check if the connection string is expired"
             exit 1
           fi
           
